config/routes.rb
Rails.application.routes.draw do
  resources :pins
  resources :pins
  devise_for :users
  get 'home' => "pages#home"
  root "pages#home"
  get 'about' => "pages#about"
  get 'portfolio' => "pages#portfolio"
  get 'sample' => "pages#sample"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
 	# now can call @pin.user
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # attr_accessor :name, :email
  
  has_many :pins
end


class AddUserIdToPins < ActiveRecord::Migration
  def change
    add_column :pins, :user_id, :integer
    add_index :pins, :user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  	pdf_filename = File.join(Rails.root, "tmp/resume.pdf")
  	send_file(pdf_filename, :filename => "resume.pdf", :disposition => "application/pdf")
  end

 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  #Read All
  def index
    @pins = Pin.all
  end

  # Read action
  def show
  end

  def new
    @pin = Pin.new
    # @pin = current_user.pins.build
  end

  def edit
  end

  # New + create
  def create
    @pin = Pin.new(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
    else
      render :new 
    end
  end
  # Edit + update
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.' 
      else
        render :edit 
      end
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      redirect_to pins_url, notice: 'Pin was successfully destroyed.'
    end
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
   <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
              <li>
                <a href="http://www.facebook.com/JunKim0922" target= "_blank"><img src= "https://www.seeklogo.net/wp-content/uploads/2011/06/facebook-icon-logo-vector.png" width= "40" height= "40">

                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                    </span>

                </a>
            </li>
            <li>
                <a href="https://github.com/j464kim" target= "_blank"><img src= "https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png" width= "40" height= "40">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
            <li><a href= "https://www.linkedin.com/in/kwnsrnjs12" target= "_blank"><img src= "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/768px-LinkedIn_logo_initials.png" width= "40" height= "40" alt= "LinkedIn" title= "LinkedIn" /></a></li>
            
            <hr>
        </ul>
       <center> <p class="copyright text-muted">Copyright &copy; JunGwon_Kim 2016</p></center>
      </div>
    </div>
  </div>
    </footer>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 <%= link_to "PERSONAL BLOG", root_path, class: "navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home", root_path %></li>
                  <li><%= link_to "About", about_path %></li> 
                  <li><%= link_to "Portfolio", portfolio_path %></li>
                  <!-- <li><%= link_to "Sample", sample_path %></li> -->
                    <!-- # log in & log out Setting -->
      <% if user_signed_in? %>
        <li><%= link_to "Account Setting", edit_user_registration_path %><li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>

        <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background age for this header on the line below. -->
   
    <!-- Main Content -->
<hr>

    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html large="en">
<head>

	<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
<%= stylesheet_link_tag    'application', media: 'all',
  'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


  <title>Personal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
</head>
<body>

	<%= render 'layouts/header' %>

	<p></p>
<p></p>
<p></p>
	<!-- <div clsas= "main-page-content <%= controller.controller_name %>">

	</div>  -->
		<%= yield %>

<%= render 'layouts/footer' %>
	</body>
	
	</html>

app/views/pages/about.html.erb
<hr>
<center><h1>About myself..</h1></center>

  <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="http://uwaterloo.ca" class="portfolio-box">
                        <img src="/assets/waterloo" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Education
                                </div>
                                <div class="project-name">
                                    University of Waterloo
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Toronto" class="portfolio-box">
                        <img src="/assets/toronto" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    City
                                </div>
                                <div class="project-name">
                                    Toronto
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.vaniercollege.qc.ca" class="portfolio-box">
                        <img src="/assets/vanier" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Education
                                </div>
                                <div class="project-name">
                                    Cégep Vanier
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Montreal" class="portfolio-box">
                        <img src="/assets/montreal" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    City
                                </div>
                                <div class="project-name">
                                    Montreal
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://waterloohybrid.com" class="portfolio-box">
                        <img src="/assets/hybrid" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Activity
                                </div>
                                <div class="project-name">
                                    Waterloo Hybrid
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Korea" class="portfolio-box">
                        <img src="/assets/korea" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Nation
                                </div>
                                <div class="project-name">
                                    Korea
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Canada" class="portfolio-box">
                        <img src="/assets/canada" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Nation
                                </div>
                                <div class="project-name">
                                    Canada
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>JunGwon Kim</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <!-- <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!-- [if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]> -->

</head>

<body>

 <header class="intro-header" style="background-image: url(/assets/2)">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>JunGwon Kim</h1>
                        <hr class="small">
                        <span class="subheading">Welcome to Jun's Blog</span>
                        
    <P> </P>
    <% if user_signed_in? %>
       <!-- do something -->
     <% else %>
        <p> 
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-default btn-lg" %> 
    <%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg" %>
        </p>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
  
 </header>

</body>

</html>

app/views/pages/portfolio.html.erb
<h1>Waterloo Hybrid</h1>

	<div class="container">
		<!-- # No '%=' when you don't want it to show up in the actual page -->
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<%= yield %>
	</div>
<p>

</p>

  <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="http://uwaterloo.ca" class="portfolio-box">
                        <img src="/assets/waterloo" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Education
                                </div>
                                <div class="project-name">
                                    University of Waterloo
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Toronto" class="portfolio-box">
                        <img src="/assets/toronto" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    City
                                </div>
                                <div class="project-name">
                                    Toronto
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://www.vaniercollege.qc.ca" class="portfolio-box">
                        <img src="/assets/vanier" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Education
                                </div>
                                <div class="project-name">
                                    Cégep Vanier
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Montreal" class="portfolio-box">
                        <img src="/assets/montreal" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    City
                                </div>
                                <div class="project-name">
                                    Montreal
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="http://waterloohybrid.com" class="portfolio-box">
                        <img src="/assets/hybrid" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Activity
                                </div>
                                <div class="project-name">
                                    Waterloo Hybrid
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Korea" class="portfolio-box">
                        <img src="/assets/korea" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Nation
                                </div>
                                <div class="project-name">
                                    Korea
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="https://en.wikipedia.org/wiki/Canada" class="portfolio-box">
                        <img src="/assets/canada" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Nation
                                </div>
                                <div class="project-name">
                                    Canada
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

app/views/pages/sample.html.erb
<h1>About myself</h1>
<h2></h2>
<p></p>
<p></p>

<!DOCTYPE html>
<html large="en">
<head>
<title> hello to my app </title>
<meta charset="utf-8" />
 <!-- internal style sheet -->

<style>
body {
    background : #CBBB9B;
    margin : 0;
    padding : 0;
    font-family : "Helvetica", "Arial";
}
#wrapper {
    width : 960px;
    height : auto;
    background : #DAD5C1;
    border-left : 5px solid #A09885;
    border-right : 5px solid #A09885;
    overflow : 0 auto;
    padding : 100px;
}
#header {
    width : 100%;
    height : 100px;
    border-bottom : 3px solid #7C7063;
}
#logo {
    float : left;
    margin : -80px 30px 0px -80px;
}
#social {
    float : right;
    margin : -350px 30px 100px 1100px;
}
#social ul li {
    float : left;
    list-style : none; /*hide bullet point*/
    padding-right : 2px;
}
#social img {

    height : 40px;
    width : 40px;
}

/* section of the page and designating certain html element*/
/*id once on a page, class multiple times*/
</style>
</head>

<body>

<div id="wrapper">
    <div id="header">
        <a name= "top"></a> <!-- retrun to the top page -->
        <div id="logo">
            <!-- image source  -->
            <img src="http://likecool.com/Gear/Pic/One%20Trippy%20Profile%20Pic/One-Trippy-Profile-Pic.jpg" width= "350" height= "250" alt="Logo" title="JunGwon Kim">
        </div>     <!-- end of logo -->
            <div id= "social">
                <!-- Unordered_List  -->
                <ul>
                    <!-- List_Item, Open up a new window -->
                    <li><a href= "http://www.facebook.com/JunKim0922" target= "_blank"><img src= "https://www.seeklogo.net/wp-content/uploads/2011/06/facebook-icon-logo-vector.png" alt= "facebook" title= "facebook"/></a></li>
                    <li><a href= "https://www.linkedin.com/in/kwnsrnjs12" target= "_blank"><img src= "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/768px-LinkedIn_logo_initials.png"  alt= "LinkedIn" title= "LinkedIn"/></a></li>
                </ul>
            </div>   <!--  end of social-->
     </div>             <!-- end of header -->
        <div id= "slidebar">
            <div id= "menu">
                <ul>
                    <li><a href= "#Intro"</a></li>
                    <li><a href= "#Background"</a></li>
                    <li><a href= "#Interest"</a></li>
                    
                </ul>
            </div>      <!---End of menu--->
        </div>      <!---End of slidebar--->
    </div>      <!---End of wrapper--->
</body>

</html>


    <div class="container">
        <!-- # No '%=' when you don't want it to show up in the actual page -->
        <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>

        <%= yield %>
    </div>
<p>

</p>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
      <!--   , pin <=> , pin_path(pin) -->
        <td><%= link_to 'Show', pin %></td>
        <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>